import React from 'react'
import { Linking, SafeAreaView, ScrollView, Text, TouchableOpacity, View } from 'react-native';
import { FontAwesomeIcon } from '@fortawesome/react-native-fontawesome';
import { faAngleLeft } from '@fortawesome/pro-light-svg-icons';
import { faLocationDot } from "@fortawesome/free-solid-svg-icons";
import { library } from '@fortawesome/fontawesome-svg-core';
import accountStyles from '../AccountStyles'
library.add(faAngleLeft, faLocationDot)

const Terms = ({ navigation, styles, modal }) => {

    return (
        <SafeAreaView style={styles.screenWrapper}>
            <View style={{ flex: 1, paddingHorizontal: 18 }}>
                {!modal && (
                    <>
                        <TouchableOpacity style={[styles.circleButton, accountStyles.backButton]} onPress={() => navigation.navigate('Account', { screen: 'Home'})}>
                            <FontAwesomeIcon icon={['fal', 'angle-left']} size={20} />
                        </TouchableOpacity>
                        <Text style={[ styles.pageHeader, { paddingBottom: 14 } ]}>Terms</Text>
                    </>
                )}
                
                <ScrollView style={{ marginBottom: 14 }}>
                    <Text style={accountStyles.legalText}>Welcome to the Road Trip NFT video game services, which are accessible via the Road Trip NFT, LLC (“Road Trip NFT”) web and mobile applications (the “App”). To make these Road Trip Terms of Service (the “Terms”) easier to read, our video game services, the App, and our websites located at <Text style={styles.link} onPress={() => {Linking.openURL('https://www.roadtripnft.com')}}>https://www.roadtripnft.com</Text> (the “Site”) are collectively called the “Services.” Please read carefully these Terms and our Privacy Policy, because they govern your use of our Services.</Text>

                    <Text style={accountStyles.legalHeader}>Agreement to Terms</Text>
                    <Text style={accountStyles.legalText}>By using our Services, you are agreeing to these Terms and our Privacy Policy. If you are the parent or legal guardian of a child under the age of 13 (the “Parent”), you are agreeing to these Terms on behalf of yourself and your child(ren) who are authorized to use the Services pursuant to these Terms and in our Privacy Policy. If you don’t agree to these Terms and our Privacy Policy, do not use the Services.</Text>

                    <Text style={accountStyles.legalHeader}>Changes to Terms or Services</Text>
                    <Text style={accountStyles.legalText}>We may modify these Terms at any time. If we do so, we’ll let you know either by posting the modified Terms on the Site or App or through other communications. It’s important that you review the Terms whenever we modify them, because if you continue to use the Services after we have posted modified Terms on the Site or App, or otherwise communicate them to you, you are indicating to us that you agree to be bound by the modified Terms. If you don’t agree to be bound by the modified Terms, then you may not use the Services anymore. Because our Services evolve over time, we may change or discontinue all or any part of the Services at any time and without notice.</Text>

                    <Text style={accountStyles.legalHeader}>Changes to Terms or Services</Text>
                    <Text style={accountStyles.legalText}>We may modify these Terms at any time. If we do so, we’ll let you know either by posting the modified Terms on the Site or App or through other communications. It’s important that you review the Terms whenever we modify them, because if you continue to use the Services after we have posted modified Terms on the Site or App, or otherwise communicate them to you, you are indicating to us that you agree to be bound by the modified Terms. If you don’t agree to be bound by the modified Terms, then you may not use the Services anymore. Because our Services evolve over time, we may change or discontinue all or any part of the Services at any time and without notice.</Text>

                    <Text style={accountStyles.legalText}>
                        ARBITRATION NOTICE: EXCEPT IF YOU OPT OUT AND EXCEPT FOR CERTAIN TYPES OF DISPUTES DESCRIBED IN THE “AGREEMENT TO ARBITRATE” SECTION BELOW, YOU AGREE THAT DISPUTES BETWEEN YOU AND ROAD TRIP NFT WILL BE RESOLVED BY BINDING, INDIVIDUAL ARBITRATION, AND YOU ARE WAIVING YOUR RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS ACTION OR REPRESENTATIVE PROCEEDING.
                    </Text>

                    <Text style={accountStyles.legalHeader}>Privacy</Text>
                    <Text style={accountStyles.legalText}>Please refer to our <Text style={styles.link} onPress={() => {Linking.openURL('https://www.roadtripnft.com/privacy')}}>https://www.roadtripnft.com/privacy</Text> for information on how we collect, use, and disclose information from our users.</Text>

                    <Text style={accountStyles.legalHeader}>Eligibility and Account Registration</Text>
                    <Text style={accountStyles.legalText}>If you want to use certain features of the Services, you will have to create an account with us (an “Account”). You can create an Account if you have (a) an email address; (b) a pre-existing Roadtripper (“RT”) account; or (c) such other pre-existing third-party accounts as we may choose to support in the future (notification of which will be provided by allowing selection of such pre-existing accounts on the relevant account-creation screen). We will create your Account by extracting from your Email, RT, or other pre-existing third-party account certain personal information (such as your email address) that your privacy settings on the applicable account permit us to access.</Text>
                    <Text style={accountStyles.legalText}>It’s important that you provide us with accurate, complete, and up-to-date information for your Account, and you agree to update such information as needed, to keep it accurate, complete, and up-to-date. If you don’t, we might have to suspend or terminate your Account. You agree that you won’t disclose your Account password to anyone and you’ll notify us immediately of any unauthorized use of your Account. You’re responsible for all activities that occur under your Account, whether or not you know about them.</Text>
                    <Text style={accountStyles.legalText}>Accounts made available through this website are available only to (1) persons of legal age to form a binding contract and who are not a person barred from receiving services under the laws of the United States or other applicable jurisdictions, or (2) in their discretion, their minor child over the age of 13. If you are a minor over the age of 13, your parent or guardian must complete the registration process, in which case they will take full responsibility for all obligations under this Agreement. Under no circumstances will an account made available through this website be available to minors under the age of 13. By registering, you represent that you are a person of legal age to form a binding contract and are not a person barred from receiving services under the laws of the United States or other applicable jurisdictions and are either accepting these Terms of Use on behalf of yourself or your child. You may not transfer or share your account with anyone, except that if you are a parent or guardian, you may permit one child over the age of 13 to use the account instead of you (in which case you may not use that account). You are liable for all activities conducted through the account, and parents or guardians are liable for the activities of their child.</Text>

                    <Text style={accountStyles.legalHeader}>Safe Play</Text>
                    <Text style={accountStyles.legalText}>During use of our App, please be aware of your surroundings and play safely. You agree that your use of the App and play of the game is at your own risk, and it is your responsibility to maintain such health, liability, hazard, personal injury, medical, life, and other insurance policies as you deem reasonably necessary for any injuries that you may incur while using the Services. You also agree not to use the App to violate any applicable law, rule, or regulation (including but not limited to the laws of trespass) and you agree not to encourage or enable any other individual to violate any applicable law, rule, or regulation. Without limiting the foregoing, you agree that in conjunction with your use of the App you will not inflict emotional distress on other people, will not humiliate other people (publicly or otherwise), will not assault or threaten other people, will not enter onto private property without permission, will not impersonate any other person or misrepresent your affiliation, title, or authority, and will not otherwise engage in any activity that may result in injury, death, property damage, and/or liability of any kind. To the extent permitted by applicable law, Road Trip NFT disclaims all liability related to any property damage, personal injury, or death that may occur during your use of our Services, including any claims based on the violation of any applicable law, rule, or regulation or your alleged negligence or other tort liability. Further, in the event that you have a dispute with one or more other users of the App, you release Road Trip NFT (and our officers, directors, agents, subsidiaries, joint ventures, and employees) from all claims, demands, and damages (actual and consequential) of every kind and nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way connected with such disputes.</Text>

                    <Text style={accountStyles.legalHeader}>Rights in App</Text>
                    <Text style={accountStyles.legalText}>Subject to your compliance with these Terms, Road Trip NFT grants you a limited nonexclusive, nontransferable, non-sublicensable license to download and install a copy of the App on a mobile device and to run such copy of the App solely for your own personal, noncommercial purposes. Except as expressly permitted in these Terms, you may not: (a) copy, modify, or create derivative works based on the App; (b) distribute, transfer, sublicense, lease, lend, or rent the App to any third party; (c ) reverse engineer, decompile, or disassemble the App; or (d) make the functionality of the App available to multiple users through any means. Road Trip NFT reserves all rights in and to the App not expressly granted to you under these Terms.</Text>

                    <Text style={accountStyles.legalHeader}>Additional Terms for App Store Apps</Text>
                    <Text style={accountStyles.legalText}>If you accessed or downloaded the App from the Apple Store, then you agree to use the App only: (a) on an Apple-branded product or device that runs iOS (Apple’s proprietary operating system software); and (b) as permitted by the “Usage Rules” set forth in the Apple Store Terms of Service.</Text>
                    <Text style={accountStyles.legalText}>
                    If you accessed or downloaded the App from any app store or distribution platform (like the Apple Store, Google Play, or Amazon Appstore) (each, an “App Provider”), then you acknowledge and agree that:</Text>


                    <Text style={accountStyles.legalHeader}>Content and Content Rights</Text>
                    <Text style={accountStyles.legalText}>For purposes of these Terms: (a) “Content” means the text, software, scripts, graphics, photos, sounds, music, videos, audiovisual combinations, interactive features, works of authorship of any kind, and information or other materials that are posted, generated, provided, or otherwise made available through the Services; and (b) “User Content” means any Content that Account holders (including you) provide to be made available through the Services. Content includes without limitation User Content. Subject to your compliance with these Terms, Road Trip NFT grants you a personal, noncommercial, nonexclusive, nontransferable, non-sublicensable, revocable license to download, view, display, and use the Content solely in connection with your permitted use of the Services.</Text>

                    <Text style={accountStyles.legalHeader}>Content Ownership</Text>
                    <Text style={accountStyles.legalText}>Road Trip NFT does not claim any ownership rights in any User Content, and nothing in these Terms will be deemed to restrict any rights that you may have to use and exploit your User Content. Subject to the foregoing, Road Trip NFT and its licensors exclusively own all right, title, and interest in and to the Services and Content, including all associated intellectual property rights. You acknowledge that the Services and Content are protected by copyright, trademark, and other laws of the United States and foreign countries. You agree not to remove, alter, or obscure any copyright, trademark, service mark, or other proprietary rights notices incorporated in or accompanying the Services or Content.</Text>

                    <Text style={accountStyles.legalHeader}>Rights Granted By You</Text>
                    <Text style={accountStyles.legalText}>By making any User Content available through Services, you grant to Road Trip NFT a nonexclusive, perpetual, irrevocable, transferable, sublicensable, worldwide, royalty-free license to use, copy, modify, create derivative works based upon, publicly display, publicly perform, and distribute your User Content in connection with operating and providing the Services and Content to you and to other Account holders.</Text>
                    <Text style={accountStyles.legalText}>You are solely responsible for all your User Content. You represent and warrant that you own all your User Content, or you have all rights that are necessary to grant us the license rights in your User Content under these Terms. You also represent and warrant that neither your User Content, nor your use and provision of your User Content to be made available through the Services, nor any use of your User Content by Road Trip NFT on or through the Services will infringe, misappropriate, or violate a third party’s intellectual property rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation. Road Trip NFT may reject any submissions in which Road Trip NFT believes, in its sole discretion, that the User Content is inappropriate or violates these Terms. Road Trip NFT further reserves the right to remove any User Content from the Services at any time and without notice and for any reason.</Text>

                    <Text style={accountStyles.legalHeader}>Conduct, General Prohibitions, and Road Trip NFT’s Enforcement Rights</Text>
                    <Text style={accountStyles.legalText}>You agree that you are responsible for your own conduct and User Content while using the Services, and for any consequences thereof. By way of example, and not as a limitation, you agree that when using the Services and Content, you will not:</Text>
                    <ListItem>defame, abuse, harass, harm, stalk, threaten, or otherwise violate the legal rights (including the rights of privacy and publicity) of others</ListItem>
                    <ListItem>upload, post, email, transmit, or otherwise make available any unlawful, inappropriate, defamatory, obscene, pornographic, vulgar, offensive, fraudulent, false, misleading, or deceptive Content or message</ListItem>
                    <ListItem>promote or engage in discrimination, bigotry, racism, hatred, or harassment against any individual or group</ListItem>
                    <ListItem>trespass, or in any manner attempt to gain or gain access to any property or location where you do not have a right or permission to be</ListItem>
                    <ListItem>violate, or encourage any conduct that would violate, any applicable law or regulation or would give rise to civil liability</ListItem>
                    <ListItem>upload, post, or otherwise make available commercial messages or advertisements, pyramid schemes, or other disruptive notices</ListItem>
                    <ListItem>impersonate or misrepresent your affiliation with another person or entity</ListItem>
                    <ListItem>promote or provide instructional information about illegal or harmful activities or substances</ListItem>
                    <ListItem>promote or engage in physical harm, violence, or injury against any group or individual;</ListItem>
                    <ListItem>transmit any viruses, worms, defects, Trojan horses, or any items of a destructive nature</ListItem>
                    <ListItem>submit fake, falsified, misleading, or inappropriate data submissions, edits, or removals</ListItem>
                    <ListItem>post, upload, publish, submit, or transmit any Content that infringes, misappropriates, or violates a third party’s patent, copyright, trademark, trade secret, moral rights, or other intellectual property rights, or rights of publicity or privacy;</ListItem>
                    <ListItem>use, display, mirror, or frame the Services or any individual element within the Services, Road Trip NFT’s name, any Road Trip NFT trademark, logo, or other proprietary information, or the layout and design of any page or form contained on a page, without Road Trip NFT’s express written consent</ListItem>
                    <ListItem>access, tamper with, or use nonpublic areas of the Services, Road Trip NFT’s computer systems, or the technical delivery systems of Road Trip NFT’s providers</ListItem>
                    <ListItem>attempt to probe, scan, or test the vulnerability of any Road Trip NFT system or network or breach any security or authentication measures</ListItem>
                    <ListItem>avoid, bypass, remove, deactivate, impair, descramble, or otherwise circumvent any technological measure implemented by Road Trip NFT or any of Road Trip NFT’s providers or any other third party (including another user) to protect the Services or Content</ListItem>
                    <ListItem>attempt to access or search the Services or Content, or download Content from the Services through the use of any technology or means other than those provided by Road Trip NFT or other generally available third-party web browsers (including, without limitation, automation software, bots, spiders, crawlers, data-mining tools, or hacks, tools, agents, engines, or devices of any kind)</ListItem>
                    <ListItem>extract, scrape, index, copy, or mirror the Services or Content or portions thereof (including but not limited to the Road Trip NFT database and other information about users or gameplay)</ListItem>
                    <ListItem>use any meta tags or other hidden text or metadata utilizing a Road Trip NFT trademark, logo, URL, or product name without Road Trip NFT’s express written consent</ListItem>
                    <ListItem>forge any TCP/IP packet header or any part of the header information in any email or newsgroup posting, or in any way use the Services or Content to send altered, deceptive, or false source-identifying information</ListItem>
                    <ListItem>attempt to decipher, decompile, disassemble, or reverse engineer any of the software used to provide the Services or Content</ListItem>
                    <ListItem>interfere with, or attempt to interfere with, the access of any user, host, or network, including, without limitation, sending a virus, overloading, flooding, spamming, or mail-bombing the Services</ListItem>
                    <ListItem>take any action that imposes, or may impose, an unreasonable or disproportionately large load on the Services or Road Trip NFT’s infrastructure;</ListItem>
                    <ListItem>delete, obscure, or in any manner alter any attribution, warning, or link that appears in the Services or the Content</ListItem>
                    <ListItem>use the Services or Content, or any portion thereof, for any commercial purpose or for the benefit of any third party or in a manner not permitted by these Terms, including but not limited to (a) gathering in App items or resources for sale outside the App, (b) performing services in the App in exchange for payment outside the App, or (c ) sell, resell, rent, or lease the App or your Account</ListItem>
                    <ListItem>collect or store any personally identifiable information from the Services from other users of the Services without their express permission</ListItem>
                    <ListItem>violate any applicable law or regulation</ListItem>
                    <ListItem>encourage or enable any other individual to do any of the foregoing</ListItem>

                    <Text style={accountStyles.legalText}>Although we’re not obligated to monitor access to or use of the Services or Content or to review or edit any Content, we have the right to do so for the purpose of operating the Services, to ensure compliance with these Terms, and to comply with applicable law or other legal requirements. We reserve the right, but are not obligated, to remove or disable access to any Content, at any time and without notice, including but not limited to, if we, at our sole discretion, consider any Content to be objectionable or in violation of these Terms. We have the right to investigate violations of these Terms or conduct that affects the Services. We may also consult and cooperate with law enforcement authorities to prosecute users who violate the law.</Text>

                    <Text style={accountStyles.legalHeader}>Feedback</Text>
                    <Text style={accountStyles.legalText}>We welcome feedback, comments, and suggestions for improvements to the Services (“Feedback”). You can submit Feedback by reaching out to us on Twitter, LinkedIn, by emailing us at hello@roadtripnft.com or via our products. You grant to us a nonexclusive, worldwide, perpetual, irrevocable, fully paid, royalty free, sublicensable, and transferable license under any and all intellectual property rights that you own or control to use, copy, modify, create derivative works based upon, and otherwise exploit the Feedback for any purpose.</Text>

                    <Text style={accountStyles.legalHeader}>Links to Third Party Websites or Resources</Text>
                    <Text style={accountStyles.legalText}>The Services and App may contain links to third-party websites or resources. We provide these links only as a convenience and are not responsible for the content, products, or services on or available from those websites, or resources or links displayed on such websites. You acknowledge sole responsibility for and assume all risk arising from your use of any third-party websites or resources.</Text>

                    <Text style={accountStyles.legalHeader}>Termination</Text>
                    <Text style={accountStyles.legalText}>We may terminate your access to and use of the Services, at our sole discretion, at any time and without notice to you. You may cancel your Account at any time by accessing the Road Trip NFT Account Settings Help Center or via our mobile apps. Upon any termination, discontinuation, or cancellation of Services or your Account, the following provisions of these Terms will survive: Arbitration Notice; Content Ownership; Rights Granted by You; Effect of Termination on Trading Items, Virtual Money, and Virtual Goods; Feedback; Disclaimer of Warranties; Indemnity; Limitation of Liability; Dispute Resolution; General Terms; and this sentence of Termination.</Text>

                    <Text style={accountStyles.legalHeader}>Disclaimer of Warranties</Text>
                    <Text style={accountStyles.legalText}>YOUR USE OF THE APP AND SERVICES ARE AT YOUR OWN RISK. TO THE EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICES AND CONTENT ARE PROVIDED “AS IS,” WITHOUT WARRANTY OF ANY KIND. WITHOUT LIMITING THE FOREGOING, ROAD TRIP NFT, EXPLICITLY DISCLAIM ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE. Road Trip NFT makes no warranty that the Services will meet your requirements or be available on an uninterrupted, secure, or error -free basis, and we make no warranty regarding the quality, accuracy, timeliness, truthfulness, completeness, or reliability of any Content.</Text>
                    <Text style={accountStyles.legalText}>YOU ASSUME ALL RISKS RELATING TO YOUR ONLINE OR OFFLINE COMMUNICATIONS AND INTERACTIONS WITH OTHER USERS OF THE SERVICES AND WITH OTHER PERSONS WITH WHOM YOU COMMUNICATED OR INTERACT AS A RESULT OF YOUR USE OF THE SERVICES. YOU UNDERSTAND THAT ROAD TRIP NFT DOES NOT SCREEN OR INQUIRE INTO THE BACKGROUND OF ANY USERS OF THE SERVICES. ROAD TRIP NFT MAKES NO REPRESENTATIONS OR WARRANTIES AS TO THE CONDUCT OF USERS OF THE SERVICES. YOU AGREE TO TAKE REASONABLE PRECAUTIONS IN ALL COMMUNICATIONS AND INTERACTIONS WITH OTHER USERS OF THE SERVICES AND WITH OTHER PERSONS WITH WHOM YOU COMMUNICATE OR INTERACT AS A RESULT OF YOUR USE OF THE SERVICES, PARTICULARLY IF YOU DECIDE TO MEET OFFLINE OR IN PERSON.</Text>

                    <Text style={accountStyles.legalHeader}>Indemnity</Text>
                    <Text style={accountStyles.legalText}>You will indemnify and hold harmless Road Trip NFT and their respective officers, directors, employees, and agents, from and against any claims, disputes, demands, liabilities, damages, losses, and costs and expenses, including, without limitation, reasonable legal and accounting fees arising out of or in any way connected with (a) your access to or use of the Services or Content, (b) your User Content, or (c ) your violation of these Terms.</Text>

                    <Text style={accountStyles.legalHeader}>Limitation of Liability</Text>
                    <Text style={accountStyles.legalText}>TO THE EXTENT PERMITTED BY APPLICABLE LAW, NEITHER Road Trip NOR TPC OR TPCI OR ANY OTHER PARTY INVOLVED IN CREATING, PRODUCING, OR DELIVERING THE SERVICES OR CONTENT WILL BE LIABLE TO YOU FOR ANY INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, EXEMPLARY, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, LOSS OF DATA, OR GOODWILL, SERVICE INTERRUPTION, COMPUTER DAMAGE, OR SYSTEM FAILURE OR THE COST OF SUBSTITUTE SERVICES, ARISING OUT OF OR IN CONNECTION WITH THESE TERMS, OR FROM THE USE OF OR INABILITY TO USE THE SERVICES OR CONTENT, OR FROM ANY COMMUNICATIONS, INTERACTIONS, OR MEETINGS WITH OTHER USERS OF THE SERVICES OR PERSONS WITH WHOM YOU COMMUNICATE OR INTERACT AS A RESULT OF YOUR USE OF THE SERVICES, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT Road Trip NFT HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, EVEN IF A LIMITED REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION.</Text>
                    <Text style={accountStyles.legalText}>IN NO EVENT WILL THE TOTAL LIABILITY OF ROAD TRIP NFT ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR FROM THE USE OF OR INABILITY TO USE THE SERVICES OR CONTENT EXCEED ONE THOUSAND DOLLARS ($1,000). THE EXCLUSIONS AND LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN ROAD TRIP NFT AND YOU.</Text>

                    <Text style={accountStyles.legalHeader}>Dispute Resolution</Text>
                    <Text style={[accountStyles.legalText, styles.bold]}>Governing Law</Text>
                    <Text style={accountStyles.legalText}>These Terms and any action related thereto will be governed by the laws of the State of Georgia without regard to its conflict of laws provisions.</Text>
                    <Text style={[accountStyles.legalText, styles.bold]}>Agreement to Arbitrate</Text>
                    <Text style={accountStyles.legalText}>You and Road Trip NFT agree that any dispute, claim, or controversy arising out of or relating to these Terms or the breach, termination, enforcement, interpretation, or validity thereof or the use of the Services or Content (collectively, “Disputes”) will be settled by binding arbitration, except that each party retains the right: (a) to bring an individual action in small claims court and (b) to seek injunctive or other equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation, or violation of a party’s copyrights, trademarks, trade secrets, patents, or other intellectual property rights (the action described in this clause (b), an “IP Protection Action”). Without limiting the preceding sentence, you will also have the right to litigate any other Dispute if you provide Road Trip NFT with written notice of your desire to do so by email or regular mail at legal@Roadtripnft.com or 30 5th Street NE UNIT 1005, Atlanta, GA 30308 within thirty (30) days following the date you first accept these Terms (such notice, an “Arbitration Opt-out Notice”). If you don’t provide Road Trip NFT with an Arbitration Opt-out Notice within the thirty (30) day period, you will be deemed to have knowingly and intentionally waived your right to litigate any Dispute except as expressly set forth in clauses (a) and (b) above. The exclusive jurisdiction and venue of any IP Protection Action or, if you timely provide Road Trip NFT with an Arbitration Opt-out Notice, will be the state and federal courts located in Georgia, and each of the parties hereto waives any objection to jurisdiction and venue in such courts. Unless you timely provide Road Trip NFT with an Arbitration Opt-out Notice, you acknowledge and agree that you and Road Trip NFT are each waiving the right to a trial by jury or to participate as a plaintiff or class member in any purported class action or representative proceeding. Further, unless both you and Road Trip NFT otherwise agree in writing, the arbitrator may not consolidate more than one person’s claims, and may not otherwise preside over any form of any class or representative proceeding. If this specific paragraph is held unenforceable, then the entirety of this “Dispute Resolution” section will be deemed void. Except as provided in the preceding sentence, this “Dispute Resolution” section will survive any termination of these Terms.</Text>
                    <Text style={[accountStyles.legalText, styles.bold]}>Arbitration Rules</Text>
                    <Text style={accountStyles.legalText}>The arbitration will be administered by the American Arbitration Association (“AAA”) in accordance with the Commercial Arbitration Rules and the Supplementary Procedures for Consumer Related Disputes (the “AAA Rules”) then in effect, except as modified by this “Dispute Resolution” section. (The AAA Rules are available at www.adr.org/arb_med or by calling the AAA at 1-800-778-7879.) The Federal Arbitration Act will govern the interpretation and enforcement of this Section.</Text>
                    <Text style={[accountStyles.legalText, styles.bold]}>Arbitration Process</Text>
                    <Text style={accountStyles.legalText}>A party who desires to initiate arbitration must provide the other party with a written Demand for Arbitration as specified in the AAA Rules. (The AAA provides a general Demand for Arbitration ) The arbitrator will be either a retired judge or an attorney licensed to practice law and will be selected by the parties from the AAA’s roster of arbitrators. If the parties are unable to agree upon an arbitrator within seven (7) days of delivery of the Demand for Arbitration, then the AAA will appoint the arbitrator in accordance with the AAA Rules.</Text>
                    <Text style={[accountStyles.legalText, styles.bold]}>Arbitration Location and Procedure</Text>
                    <Text style={accountStyles.legalText}>Unless you and Road Trip NFT otherwise agree, the arbitration will be conducted in the county where you reside. If your claim does not exceed $10,000, then the arbitration will be conducted solely on the basis of the documents that you and Road Trip NFT submit to the arbitrator, unless you request a hearing or the arbitrator determines that a hearing is necessary. If your claim exceeds $10,000, your right to a hearing will be determined by the AAA Rules. Subject to the AAA Rules, the arbitrator will have the discretion to direct a reasonable exchange of information by the parties, consistent with the expedited nature of the arbitration.</Text>
                    <Text style={[accountStyles.legalText, styles.bold]}>Arbitrator's Decision</Text>
                    <Text style={accountStyles.legalText}>The arbitrator will render an award within the time frame specified in the AAA Rules. The arbitrator’s decision will include the essential findings and conclusions upon which the arbitrator based the award. Judgment on the arbitration award may be entered in any court having jurisdiction thereof. The arbitrator’s award of damages must be consistent with the terms of the “Limitation of Liability” section above as to the types and amounts of damages for which a party may be held liable. The arbitrator may award declaratory or injunctive relief only in favor of the claimant and only to the extent necessary to provide relief warranted by the claimant’s individual claim. If you prevail in arbitration, you will be entitled to an award of attorneys’ fees and expenses to the extent provided under applicable law. Road Trip NFT will not seek, and hereby waives, all rights it may have under applicable law to recover attorneys’ fees and expenses if it prevails in arbitration.</Text>
                    <Text style={[accountStyles.legalText, styles.bold]}>Fees</Text>
                    <Text style={accountStyles.legalText}>Our responsibility to pay any AAA filing, administrative, and arbitrator fees will be solely as set forth in the AAA Rules. However, if your claim for damages does not exceed $75,000, Road Trip NFT will pay all such fees unless the arbitrator finds that either the substance of your claim or the relief sought in your Demand for Arbitration was frivolous or was brought for an improper purpose (as measured by the standards set forth in Federal Rules of Civil Procedure 11(b)).</Text>
                    <Text style={[accountStyles.legalText, styles.bold]}>Changes</Text>
                    <Text style={accountStyles.legalText}>Notwithstanding the provisions of the “Changes to Terms or Services” section above, if Road Trip NFT changes this “Dispute Resolution” section after the date you first accepted these Terms (or accepted any subsequent changes to these Terms), you may reject any such change by sending us written notice (including by email to legal@roadtripnft.com) within 30 days of the date such change became effective, as indicated in the “Last Updated” date above or in the date of Road Trip NFT’s email to you notifying you of such change. By rejecting any change, you are agreeing that you will arbitrate any Dispute between you and Road Trip NFT in accordance with the provisions of this “Dispute Resolution” section as of the date you first accepted these Terms (or accepted any subsequent changes to these Terms).</Text>

                    <Text style={accountStyles.legalHeader}>General Terms</Text>
                    <Text style={accountStyles.legalText}>These Terms and any action related thereto will be governed by the laws of the State of Georgia without regard to its conflict of laws provisions. These Terms constitute the entire and exclusive understanding and agreement between Road Trip and you regarding the Services and Content, and these Terms supersede and replace any and all prior oral or written understandings or agreements between Road Trip NFT and you regarding the Services and Content. If any provision of these Terms is held invalid or unenforceable (either by an arbitrator appointed pursuant to the terms of the “Dispute Resolution” section above or by a court of competent jurisdiction, but only if you timely opt out of arbitration by sending us an Arbitration Opt-out Notice in accordance with the terms set forth above), that provision will be enforced to the maximum extent permissible, and the other provisions of these Terms will remain in full force and effect. You may not assign or transfer these Terms, by operation of law or otherwise, without Road Trip NFT’s prior written consent. Any attempt by you to assign or transfer these Terms without such consent will be null. Road Trip NFT may freely assign or transfer these Terms without restriction. Subject to the foregoing, these Terms will bind and inure to the benefit of the parties, their successors and permitted assigns.</Text>
                    <Text style={accountStyles.legalText}>Any notices or other communications provided by Road Trip NFT under these Terms, including those regarding modifications to these Terms, will be given: (a) via email, or (b) by posting to the Services. For notices made by email, the date of receipt will be deemed the date on which such notice is transmitted.</Text>
                    <Text style={accountStyles.legalText}>Road Trip NFT’s failure to enforce any right or provision of these Terms will not be considered a waiver of such right or provision. The waiver of any such right or provision will be effective only if in writing and signed by a duly authorized representative of Road Trip NFT. Except as expressly set forth in these Terms, the exercise by either party of any of its remedies under these Terms will be without prejudice to its other remedies under these Terms or otherwise.</Text>
                    <Text style={[accountStyles.legalText, { marginTop: 14}]}>If you have any questions about these Terms or the Services, please contact Road Trip NFT at legal@roadtripnft.com or 30 5th Street NE UNIT 1005, Atlanta, GA 30308.</Text>
                </ScrollView>
            </View>
        </SafeAreaView>
    )
}

export default Terms


const ListItem = ({ children }) => {
    return (
        <View style={{flexDirection: 'row'}}>
            <Text>{'\u2022'}</Text>
            <Text style={[accountStyles.legalText, {flex: 1, paddingLeft: 5}]}>{children}</Text>
        </View>
    )
}